name: IIO Sim

on: [push, pull_request]

jobs:
  specific:
    name: With ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ["4.9.1", "4.19.1", "5.9.6", "latest"]
    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: |
        uname -a
        sudo apt-get update
        sudo apt-get -y install libelf-dev
    - name: Build w/ specific kernel version
      run: |
        install -d linux
        python3 fetch_linux.py ${{ matrix.version }} - | tar -C linux --strip-components=1 -xJ
        make -C linux defconfig
        echo "CONFIG_IIO=y" >> linux/.config
        echo "CONFIG_IIO_BUFFER=y" >> linux/.config
        make -C linux olddefconfig
        make -C linux modules_prepare
        make KERNELDIR="$PWD/linux"
        /usr/sbin/modinfo *.ko
